### ISSUE TITLE
How to show failed test?

### ISSUE THREAD

**Issue by katopz** [dumbmatter/backboard#3]
Refer to... (which I add `'Not Bob'` to make it fail)
```js
    it('should allow access of newly-created stores on upgradeDB', () => {
        return backboard.open('test', 1, upgradeDB => {
                upgradeDB.createObjectStore('players', {keyPath: 'pid', autoIncrement: true});

                upgradeDB.players.put({pid: 2, name: 'Bob'})
                    .then(() => upgradeDB.players.get(2))
                    .then((player) => assert.equal(player.name, 'Not Bob'));
            })
            .then(db => db.close());
    });
```
Will throw this via console
```
Uncaught (in promise) AssertionError {name: "AssertionError", actual: "Bob", expected: "Not Bob", operator: "==", message: ""Bob" == "Not Bob""…}
```
But still appear `green` result in test result? it should be `red`? Any hint is welcome.

Thanks

**Comment by dumbmatter** [comment]
Thanks for posting this!

It's green because that error does not abort the transaction, the error is async so try/catch will not find it, and the promise is not returned (which is what the "uncaught error" is about).

If you actually cause an IDB error (like adding two records with the same primary key) then you will see the transaction abort, even if you don't return the promises. That's IDB magic - transaction committing and aborting is automatic, you don't have to explicitly wait for anything. The tricky part is, there's not a 1-to-1 relationship between IDB and promises, so it's not always clear what "resolve" and "reject" correspond to.

I think a good solution to this would be to make transactions automatically abort and reject if there is an error inside them. I don't think I'd ever want a transaction to commit when there is an error in my code, but that is what IDB does by default (unless the error is related specifically to IDB). I'll play around with this functionality, write some tests, and if it all looks good, I'll do a new release.

I'll also have to add some documentation about how this can happen if a promise chain has a non-IDB error and isn't returned.

**Comment by katopz** [comment]
@dumbmatter Cool, many thanks for explanation! I just start exploring about testing in js. so tricky!

**Comment by dumbmatter** [comment]
Yeah, async vs sync can get confusing, and IndexedDB makes it even more confusing than that!
